import{S as g,i as h}from"./assets/vendor-BrddEoy-.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const b="46204158-4df5f152d7953f3c8acc30a03",L="https://pixabay.com/api/";async function w(t,o=1,n=12){const s=`${L}?key=${b}&q=${encodeURIComponent(t)}&image_type=photo&orientation=horizontal&safesearch=true&page=${o}&per_page=${n}`;try{const e=await fetch(s);if(!e.ok)throw new Error("Error fetching data");return(await e.json()).hits}catch(e){throw console.error("Error:",e),e}}let i;function $(){const t=document.querySelector(".gallery");t.innerHTML=""}function S(t){const o=document.querySelector(".gallery"),n=t.map(({webformatURL:s,largeImageURL:e,tags:r,likes:a,views:m,comments:p,downloads:y})=>`
    <a class="gallery__item" href="${e}">
      <img class="gallery__image" src="${s}" alt="${r}" loading="lazy" />
      <div class="info">
        <p class="info-item"><b>Likes:</b> ${a}</p>
        <p class="info-item"><b>Views:</b> ${m}</p>
        <p class="info-item"><b>Comments:</b> ${p}</p>
        <p class="info-item"><b>Downloads:</b> ${y}</p>
      </div>
    </a>`).join("");o.insertAdjacentHTML("beforeend",n),i?i.refresh():i=new g(".gallery a")}function c(t){h.error({title:"Error",message:t})}const v=document.querySelector(".search-form"),q=document.querySelector('input[name="searchQuery"]'),d=document.querySelector(".loader");let l=1,u="";function P(){d.classList.add("visible")}function f(){d.classList.remove("visible")}v.addEventListener("submit",async t=>{t.preventDefault();const o=q.value.trim();if(!o){c("Please enter a search term.");return}u=o,l=1,$(),P();try{const n=await w(u,l);if(f(),n.length===0){c("Sorry, there are no images matching your search query. Please try again!");return}S(n)}catch{f(),c("Something went wrong. Please try again later.")}});
//# sourceMappingURL=index.js.map
